### ISSUE TITLE
Package not available in Melpa or Quelpa

### ISSUE THREAD

**Issue by CsBigDataHub** [iquiw/lsp-yaml#8]
Please provide alternative installations steps like -

` :load-file` step in use-package after cloning the repo

**Comment by iquiw** [comment]
@CsBigDataHub Thanks for bringing it out.

I am still considering how to provide `yaml-language-server` specific requests, such as `json/schemaAssociations`, `yaml/registerCustomSchemaRequest`.
Also wondering if the current representation of the customize variables is good or not.
That is, I think this is not stable yet.

After some of these concerns are resolved, I think it is better to put `lsp-yaml` in [lsp-mode](https://github.com/emacs-lsp/lsp-mode) repository.

CC: @yyoncho (Sorry to disturb you 🙇 )

**Comment by yyoncho** [comment]
@iquiw 

> Also wondering if the current representation of the customize variables is good or not.

We have some helper on that, you may take a look at lsp-pyls.el for example(they are pretty much a replacement of the `lsp-yaml--settings` method). You could use methods in https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-generate-settings.el to generate the settings from a package.json.

@CsBigDataHub FTR you may use the project using quelpa, you may refer the gh repo directly, take a look here:

https://framagit.org/steckerhalter/quelpa-use-package

**Comment by CsBigDataHub** [comment]
@yyoncho @iquiw Thanks guys. Already done that. 

I just wanted @iquiw to know that the package was not available  in Melpa.

**Comment by CsBigDataHub** [comment]
Hi @iquiw . Sorry I have to re-open the issue.

I have used straight to get the package

```emacs lisp
  (use-package lsp-yaml
    :straight (lsp-yaml :type git :host github :repo "iquiw/lsp-yaml")
    :after lsp
    :config
    (add-hook 'yaml-mode-hook #'lsp))
```

I tried to do M-x lsp-yaml*

I could not find an
